### ISSUE TITLE
gzip compression?

### ISSUE THREAD

**Issue by prjemian** [areaDetector/ADSupport#10]
HDF5 supports gzip (DEFLATE) compression without external libraries.  Does the HDF5 plugin expose this and it be exposed in the user interface?

**Comment by prjemian** [comment]
see: https://support.hdfgroup.org/HDF5/hdf5-quest.html#gcomp

**Comment by ulrikpedersen** [comment]
The HDF5 library uses the external zlib library (same as gzip) for the compression implementation. So it's not strictly speaking "without external libraries" but pretty much every platform has zlib (or libz) as a fundamental package.

Yes, it is supported, exposed and documented. Look for sections on "compression" here: http://cars9.uchicago.edu/software/epics/NDFileHDF5.html

It's very easy to switch on compression. However, you'll need to play around with the HDF5 chunking configuration as each chunk is compressed in one go and these compression libraries has opinions on what buffer sizes they like to work (efficiently) on... Don't be surprised if the plugin grinds to a halt first time you switch on compression! :-)

**Comment by prjemian** [comment]
Thanks!

**Comment by MarkRivers** [comment]
Ulrik wrote:
> The HDF5 library uses the external zlib library (same as gzip) for the compression implementation. So it's not strictly speaking "without external libraries" but pretty much every platform has zlib (or libz) as a fundamental package.

Note that areaDetector/ADSupport has zlib, so it can be built on platforms for which it is not conveniently available as a system library, e.g. Windows and vxWorks.
