### ISSUE TITLE
HDF5 Header / Library version mismatch

### ISSUE THREAD

**Issue by GDYendell** [areaDetector/ADSupport#11]
I am getting the following error with Windows 64 and 32:

<pre>
W:\work\R3.14.12.3\support\ADSimDetector\iocs\win32SimDetector>bin\win32-x86\stwin32SimDetector.bat
# This file was automatically generated on Mon 08 May 2017 11:07:39 BST from
# source: /dls_sw/work/R3.14.12.3/support/ADSimDetector/etc/makeIocs/win32SimDetector.xml
#
# *** Please do not edit this file: edit the source file instead. ***
#
< envPaths
epicsEnvSet("ARCH","win32-x86")
epicsEnvSet("IOC","O.win32-x86")
epicsEnvSet("TOP","W:/work/R3.14.12.3/support/ADSimDetector/iocs/win32SimDetector")
epicsEnvSet("SUPPORT","W:/prod/R3.14.12.3/support")
epicsEnvSet("WORK","W:/work/R3.14.12.3/support")
epicsEnvSet("ADCORE","W:/work/R3.14.12.3/support/ADCore")
epicsEnvSet("ADSIMDETECTOR","W:/work/R3.14.12.3/support/ADSimDetector")
epicsEnvSet("ADSUPPORT","W:/work/R3.14.12.3/support/ADSupport")
epicsEnvSet("ASYN","W:/work/R3.14.12.3/support/asyn")
epicsEnvSet("BUSY","W:/work/R3.14.12.3/support/busy")
epicsEnvSet("CALC","W:/prod/R3.14.12.3/support/calc/3-1")
epicsEnvSet("EPICS_BASE","W:/epics/R3.14.12.3/base")
cd "W:/work/R3.14.12.3/support/ADSimDetector/iocs/win32SimDetector"
epicsEnvSet "EPICS_CA_MAX_ARRAY_BYTES", '2000000'
epicsEnvSet "EPICS_TS_MIN_WEST", '0'
# Loading libraries
# -----------------
# Device initialisation
# ---------------------
cd "W:/work/R3.14.12.3/support/ADSimDetector/iocs/win32SimDetector"
dbLoadDatabase "dbd/win32SimDetector.dbd"
win32SimDetector_registerRecordDeviceDriver(pdbbase)
# simDetectorConfig(portName, maxSizeX, maxSizeY, dataType, maxBuffers, maxMemory)
simDetectorConfig("CAM1.CAM", 1600, 1200, 1, 50, 0)
# NDStdArraysConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxMemory)
NDStdArraysConfigure("CAM1.ARR", 2, 0, "CAM1.CAM", 0, 0)
# NDFileTIFFConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers,
maxMemory)
NDFileTIFFConfigure("CAM1.TIFF", 2, 0, "CAM1.CAM", 0, 50, 0)
# NDFileJPEGConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers,
maxMemory)
NDFileJPEGConfigure("CAM1.JPEG", 2, 0, "CAM1.CAM", 0, 50, 0)
# NDFileHDF5Configure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers,
maxMemory)
NDFileHDF5Configure("CAM1.HDF", 2, 0, "CAM1.CAM", 0, 50, 0)
# NDOverlayConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, NOverlays, ma
xBuffers, maxMemory)
NDOverlayConfigure("CAM1.OVR", 2, 0, "CAM1.CAM", 0, 8, 50, 0)
# NDROIConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMe
mory)
NDROIConfigure("CAM1.ROI", 2, 0, "CAM1.CAM", 0, 50, 0)
# NDTransformConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers,
 maxMemory)
NDTransformConfigure("CAM1.TRS", 2, 0, "CAM1.CAM", 0, 50, 0)
# NDStatsConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, max
Memory)
NDStatsConfigure("CAM1.STAT", 2, 0, "CAM1.CAM", 0, 50, 0)
# FStarting iocInit
inal ioc initialisation
# ------------------------
cd "W:/work/R3.14.12.3/support/ADSimDetector/iocs/win32SimDetector"
dbLoadRecords 'db/win32SimDetector_expanded.db'
iocInit
############################################################################
## Ecas warning: Configured TCP port was unavailable.
cas warning: Using dynamically assigned TCP port 52136,
cas warning: but now two or more servers share the same UDP port.
cas warning: Depending on your IP kernel this server may not be
cas warning: reachable with UDP unicast (a host's IP in EPICS_CA_ADDR_LIST)
iocRun: All initialization complete
PICS R3.14.12.3 $Date: Mon 2012-12-17 14:11:47 -0600$
############################################################################
dbpf TESTSIMDETECTOR:CAM:NDAttributesFile, win32SimDetectorApp/data/CAM1.CAM.xml
DBR_CHAR[38]:        "win32SimDetectorApp/data/CAM1.CAM.xml"
dbpf TESTSIMDETECTOR:STAT:NDAttributesFile, win32SimDetectorApp/data/CAM1.STAT.xml
DBR_CHAR[39]:        "win32SimDetectorApp/data/CAM1.STAT.xml"
epics> Warning! ***HDF5 library version mismatched error***
The HDF5 header files used to compile this application do not match
the version used by the HDF5 library to which this application is linked.
Data corruption or segmentation faults may occur if the application continues.
This can happen when an application was compiled by one version of HDF5 but
linked with a different version of static or shared HDF5 library.
You should recompile the application or check your shared library related
settings such as 'LD_LIBRARY_PATH'.
You can, at your own risk, disable this warning by setting the environment
variable 'HDF5_DISABLE_VERSION_CHECK' to a value of '1'.
Setting it to 2 or higher will suppress the warning messages totally.
Headers are 1.10.0, library is 1.10.1
            SUMMARY OF THE HDF5 CONFIGURATION
            =================================

General Information:
-------------------
                   HDF5 Version: 1.10.1
                  Configured on: Mon May  1 12:14:51 CDT 2017
                  Configured by: epics@corvette.cars.aps.anl.gov
                    Host system: x86_64-unknown-linux-gnu
              Uname information: Linux corvette.cars.aps.anl.gov 3.10.0-514.2.2.el7.x86_64 #1 SMP Tu
e Dec 6 23:06:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
                       Byte sex: little-endian
             Installation point: /home/epics/areaDetector_libs/hdf5-1.10.1/hdf5

Compiling Options:
------------------
                     Build Mode: production
              Debugging Symbols: no
                        Asserts: no
                      Profiling: no
             Optimization Level: high

Linking Options:
----------------
                      Libraries: static, shared
  Statically Linked Executables:
                        LDFLAGS:
                     H5_LDFLAGS:
                     AM_LDFLAGS:  -L/usr/local64/lib
                Extra libraries: -lpthread -lsz -lz -ldl -lm
                       Archiver: ar
                         Ranlib: ranlib

Languages:
----------
                              C: yes
                     C Compiler: /bin/gcc ( gcc (GCC) 4.8.5 20150623 )
                       CPPFLAGS:
                    H5_CPPFLAGS: -D_GNU_SOURCE -D_POSIX_C_SOURCE=200112L   -DNDEBUG -UH5_DEBUG_API
                    AM_CPPFLAGS:  -I/usr/local64/include
                        C Flags:
                     H5 C Flags: -std=c99 -pedantic -Wall -Wextra -Wundef -Wshadow -Wpointer-arith -
Wbad-function-cast -Wcast-qual -Wcast-align -Wwrite-strings -Wconversion -Wstrict-prototypes -Wmissi
ng-prototypes -Wmissing-declarations -Wredundant-decls -Wnested-externs -Wfloat-equal -Wmissing-form
at-attribute -Wpacked -Wdisabled-optimization -Wformat=2 -Wunreachable-code -Wendif-labels -Wdeclara
tion-after-statement -Wold-style-definition -Winvalid-pch -Wvariadic-macros -Winit-self -Wmissing-in
clude-dirs -Wswitch-default -Wswitch-enum -Wunused-macros -Wunsafe-loop-optimizations -Wc++-compat -
Wlogical-op -Wlarger-than=2048 -Wvla -Wsync-nand -Wframe-larger-than=16384 -Wpacked-bitfield-compat
-Wstrict-overflow=5 -Wjump-misses-init -Wdouble-promotion -Wtrampolines -Wstack-usage=8192 -Wvector-
operation-performance  -s -Wno-inline -Wno-aggregate-return -Wno-missing-noreturn -Wno-suggest-attri
bute=const -Wno-suggest-attribute=pure -Wno-suggest-attribute=noreturn -Wno-suggest-attribute=format
 -O3
                     AM C Flags:
               Shared C Library: yes
               Static C Library: yes

                        Fortran: no

                            C++: no

                           Java: no

Features:
---------
                  Parallel HDF5: no
             High-level library: no
                   Threadsafety: yes
            Default API mapping: v110
 With deprecated public symbols: yes
         I/O filters (external): deflate(zlib),szip(encoder)
                            MPE: no
                     Direct VFD: no
                        dmalloc: no
 Packages w/ extra debug output: none
                    API tracing: no
           Using memory checker: no
Memory allocation sanity checks: no
            Metadata trace file: no
         Function stack tracing: no
      Strict file format checks: no
   Optimization instrumentation: no
Bye...
</pre>

when using the the latest ADSupport release to build the IOCs in ADSimDetector.

Do you know what the problem might be?

**Comment by MarkRivers** [comment]
```
Warning! HDF5 library version mismatched error
The HDF5 header files used to compile this application do not match
the version used by the HDF5 library to which this application is linked.
Data corruption or segmentation faults may occur if the application continues.
This can happen when an application was compiled by one version of HDF5 but
linked with a different version of static or shared HDF5 library.
You should recompile the application or check your shared library related
settings such as 'LD_LIBRARY_PATH'.
You can, at your own risk, disable this warning by setting the environment
variable 'HDF5_DISABLE_VERSION_CHECK' to a value of '1'.
Setting it to 2 or higher will suppress the warning messages totally.
Headers are 1.10.0, library is 1.10.1
```
It looks to me like it is linking with ADSupport OK, which is version 1.10.1.  However, it looks like somewhere when you build either ADCore or ADSimDetector it is finding an older 1.10.0 header file. 

H5public.h in ADSupport/include/os/WIN32 should contain these lines:
```
/* Version numbers */
#define H5_VERS_MAJOR   1       /* For major interface/format changes        */
#define H5_VERS_MINOR   10      /* For minor interface/format changes        */
#define H5_VERS_RELEASE 1       /* For tweaks, bug-fixes, or development     */
```
You should look at the build output for ADCore and ADSimDetector to see if it might have some other location in the search path where it could be finding an older version of H5public.h.

I have built and tested windows-x64-static with both Visual Studio 2010 and 2015 and it works OK for me, I don't see the errors you are getting.

**Comment by GDYendell** [comment]
I have re-built ADSupport, ADCore and ADSimDetector from scratch and the error is gone for both windows 64 and 32. I didn't realise it is necessary to do a `make clean uninstall` not just a `make clean` to remove the old header files.

Thanks @MarkRivers!
