### ISSUE TITLE
Enable HL API for HDF5

### ISSUE THREAD

**Issue by brunoseivam** [areaDetector/ADSupport#12]
Would it be possible to change the configure flag from `--disable-hl` to `--enable-hl`? ADEiger uses the HL API and it would be nice if it could get it from ADSupport.

**Comment by MarkRivers** [comment]
I can work on that.  @ulrikpedersen and @ajgdls do you recall if there was a reason that we were disabling the hl interface?  Any problem with SWMR, etc?  I have a vague recollection that there was a reason we disabled it?

**Comment by ulrikpedersen** [comment]
The combination of ```--enable-hl``` and ```--enable-threadsafe``` flags are not supported by the HDF Group. What that means is that no work have been done to check and implement thread-safety in the HL libs. Presumably if you do not use the HL lib functions from multiple threads you should be OK. 

The configuration (cmake/configure) will by default fail if you try to combine these two flags, but the ```--enable-unsupported``` flag will override that check. We do use this flag in our build of HDF5 libs at DLS as we don't use HL from multiple threads.

**Comment by MarkRivers** [comment]
I have added a new ADSupport/supportApp/hdf5_hlSrc directory.  This builds the HDF5 hl directory. @brunoseivam can you please make sure it works for your for building the Eiger detector?  I would like to release ADSupport R1-3 soon.  Thanks.

**Comment by brunoseivam** [comment]
I'll test it tomorrow and let you know

**Comment by brunoseivam** [comment]
Looks good to me :+1:

**Comment by MarkRivers** [comment]
Thanks for doing this do quickly.  I'm closing this issue.
