### ISSUE TITLE
Improve documentation for macOS

### ISSUE THREAD

**Issue by smarsching** [areaDetector/ADSupport#26]
I successfully built ADSupport 1.6 on macOS (10.13.6) with two minor changes:

First, I had to add a file `$(AREA_DETECTOR)/configure/CONFIG_SITE.local.darwin-x86` with the following content:
```
USR_INCLUDES += -I/opt/X11/include
```
This was needed so that the X11 headers can be found when building GraphicsMagick. Obviously, XQuartz also has to be installed for this headers to be present in the first place.

Second, I had to replace `$(ADSUPPORT)/supportApp/netCDFSrc/os/Darwin/config.h`, with a version created using `./configure` from the original NetCDF sources. However, I think that someone else already applied these changes just shortly after the 1.6 release, so it will probably work with the file that is in the repository now (at least, it looks very similar to the file that I generated).

Apart from these two details, everything built fine, which is great, because it makes it much simpler to build areaDetector on macOS.

**Comment by MarkRivers** [comment]
Did you use the existing `$(AREA_DETECTOR)/configure/EXAMPLE_CONFIG_SITE.local.darwin-x86?  It is old and has not been maintained much.

What did you build in ADSupport, and what did you use system libraries for (netCDF, xml2, HDF5, SZIP, TIFF, JPEG, GRAPHICSMAGICK, etc.)?  I'd like to know what has been tested to work on macOS in ADSupport, and what has not been tested.

Thanks,
Mark

**Comment by smarsching** [comment]
No, I do not use that file. I use the `EXAMPLE_CONFIG_SITE.local` as-is (simply copied it to `CONFIG_SITE.local` and use my own `CONFIG_SITE.local.darwin-x86` which only has a single line:

```
USR_INCLUDES += -I/opt/X11/include
```

This way, all the other libraries are taken from the `ADSupport` module (which - after updating the mentioned `config.h`) builds fine for me. I have a few libraries installed via Homebrew (e.g. curl), so I cannot say for sure whether `ADSupport` would also built without all of those, but still using the libraries provided by `ADSupport` looks simpler than building everything through Homebrew.

**Comment by MarkRivers** [comment]
OK, thanks.  I will change `EXAMPLE_CONFIG_SITE.local.darwin-x86` to have just that line uncommented.

**Comment by MarkRivers** [comment]
I have made the change described in the previous entry, closing issue.
