### ISSUE TITLE
MingW does not compile for IPv6 support for win32 from x86_64 linux

### ISSUE THREAD

**Issue by sudilav** [areaDetector/ADSupport#34]
Hi Team,

I haven't tried this out on a x86 linux machine but have worked on both CentOS and Ubuntu docker images. What I've found is that the MingW 32 bit compiler does not include the inet_ntoa windows function whereas the 64 bit compiler does. Here is a similar instance where it has happened to cause issues:

https://github.com/warmcat/libwebsockets/issues/100

The problem comes from supportApp/libxml2 where under the os folder/WIN32/config.h, line 120 defines IPv6 support. If I remove this line, I can build. Maybe we could have this adapted to:

#ifndef MINGW32
/* Support for IPv6 */
#define SUPPORT_IP6 /**/
#endif

Has anyone else had a successful build of areaDetector from 32bit MingW on a linux machine? I saw somewhere that the MingW 32 bit compiler does include this later on but a normal setup I'd assume would be, get linux machine, apt/dnf install MingW, get building - which for both Ubuntu and CentOS install old versions.

**Comment by MarkRivers** [comment]
> What I've found is that the MingW 32 bit compiler does not include the inet_ntoa windows function whereas the 64 bit compiler does. 

I think you mean inet_ntop, not inet_ntoa, right?  That is what the websockets issue is about, and xml2Src does not contain inet_ntoa but it does contain inet_ntop.

**Comment by sudilav** [comment]
Hey @MarkRivers,

You're right probably, always got those mixed up while I saw the errors but the fix was the fix. Since this is now merged I'll close the issue.
