### ISSUE TITLE
Add GraphicsMagick to ADSupport

### ISSUE THREAD

**Issue by MarkRivers** [areaDetector/ADSupport#7]
Currently GraphicsMagick is not supported on Windows because we no longer support ADBinaries, and GraphicsMagick is not yet built in ADSupport.  This should be added in the future.

**Comment by MarkRivers** [comment]
@pheest are you going to make a pull request to add GraphicsMagick support here?  Then I can test to see if I can reproduce the problem with XML2 on Linux.

**Comment by pheest** [comment]
I made a pull request yesterday - have you not received it?
I can make another if you wish.

**Comment by MarkRivers** [comment]
I now see that there was a pull request but you closed it, probably accidentally?

I just re-opened it.,

**Comment by pheest** [comment]
Oh!

**Comment by MarkRivers** [comment]
Closing this issue, it is now basically completed.
